version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network
    develop:
      watch:
        - path: ./frontend/src
          target: /app/src
          action: sync

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
      - NODE_ENV=production
    env_file:
      - ./server/.env
    networks:
      - app-network
    develop:
      watch:
        - path: ./server
          target: /app
          action: sync

networks:
  app-network:
    driver: bridge
